# Generated by Django 4.2.10 on 2024-02-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BondType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('maturity_length', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('yield_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bond_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustreasury.bondtype')),
            ],
        ),
        migrations.CreateModel(
            name='HeldBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustreasury.account')),
                ('daily_bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustreasury.dailybond')),
            ],
        ),
    ]
